sample_dir = "results"
sample_files = [
    ["input", "reads/hifi_reads_{sample}.fastq"],
    ["filterSeq_quality", "reports/FS_{sample}_FSQ_table.tab"],
    ["filterSeq_length", "reports/FS_{sample}_FSL_table.tab"],
	["maskPrimer_C", "reports/MP_{sample}_MPC_table.tab"],
	["maskPrimer_V", "reports/MP_{sample}_MPV_table.tab"],
    ["maskPrimers_extract", "reports/MP_{sample}_MPE_table.tab"],
    ["alignSets", "reports/AS_{sample}_AS_table.tab"],
    ["buildConsensus", "reports/BC_{sample}_BC_table.tab"],
	["total", "reports/BC_TOTAL_{sample}_headers.tab"],
    ["unique", "reports/BC_UNIQUE_{sample}_headers.tab"],
    ["unique_atleast2", "reports/BC_ATLEAST2_{sample}_headers.tab"],
    ["makedb_db-pass", "alignment/{sample}db-pass.tsv"],
    ["clone_rep_passed", "clones/{sample}rep-passed.tsv"],
]