sample_dir = "results/{sample}/{locus}"
sample_files = [
    ["input", "reads/{sample}_hifi_reads.fastq"],
    ["filterSeq_quality", "reports/{sample}/{locus}/{sample}_FS_FSQ_table.tab"],
    ["filterSeq_length", "reports/{sample}/{locus}/{sample}_FS_FSL_table.tab"],
	["maskPrimer_C", "reports/{sample}/{locus}/{sample}_MP_MPC_table.tab"],
	["maskPrimer_V", "reports/{sample}/{locus}/{sample}_MP_MPV_table.tab"],
    ["maskPrimers_extract", "reports/{sample}/{locus}/{sample}_MP_MPE_table.tab"],
    ["alignSets", "reports/{sample}/{locus}/{sample}_AS_AS_table.tab"],
    ["buildConsensus", "reports/{sample}/{locus}/{sample}_BC_BC_table.tab"],
	["total", "reports/{sample}/{locus}/{sample}_BC_TOTAL_headers.tab"],
    ["unique", "reports/{sample}/{locus}/{sample}_BC_UNIQUE_headers.tab"],
    ["unique_atleast2", "reports/{sample}/{locus}/{sample}_BC_ATLEAST2_headers.tab"],
    ["makedb_db-pass1", "alignment/{sample}/{locus}/{sample}_makedb_pass_inc_const_non-personalized.tsv"],
    ["makedb_db-pass2", "alignment/{sample}/{locus}/{sample}_makedb_pass_inc_const_personalized.tsv"],
    ["clone_rep_passed", "clones/{sample}/{locus}/{sample}_clone_rep-passed.tsv"],
]