sample_dir = "results/{sample}/{locus}"
sample_files = [
    ["filterSeq_quality", "reports/{sample}_FS_FSQ_table.tab"],
    ["filterSeq_length", "reports//{sample}_FS_FSL_table.tab"],
	["maskPrimer_C", "reports/{sample}_MP_MPC_table.tab"],
	["maskPrimer_V", "reports/{sample}_MP_MPV_table.tab"],
    ["maskPrimers_extract", "reports/{sample}_MP_MPE_table.tab"],
    ["alignSets", "reports/{sample}_AS_AS_table.tab"],
    ["buildConsensus", "reports/{sample}_BC_BC_table.tab"],
	["total", "reports/{sample}_BC_TOTAL_headers.tab"],
    ["unique", "reports/{sample}_BC_UNIQUE_headers.tab"],
    ["unique_atleast2", "reports/{sample}_BC_ATLEAST2_headers.tab"],
    ["align", "alignment/{sample}_v_align_non-personalized.tsv"],
    ["align_personalized", "alignment/{sample}_v_align_non-personalized.tsv"],
    ["clones", "clones/{sample}_{locus}_clone_freqs.csv"],
]
