sample_dir = "{sample}/{locus}"
sample_files = [
    ["filterSeq_quality", "{sample}/{locus}/reports/{sample}_FS_FSQ_table.tab"],
    ["filterSeq_length", "{sample}/{locus}/reports/{sample}_FS_FSL_table.tab"],
	["maskPrimer_C", "{sample}/{locus}/reports/{sample}_MP_MPC_table.tab"],
	["maskPrimer_V", "{sample}/{locus}/reports/{sample}_MP_MPV_table.tab"],
    ["maskPrimers_extract", "{sample}/{locus}/reports/{sample}_MP_MPE_table.tab"],
    ["alignSets", "{sample}/{locus}/reports/{sample}_AS_AS_table.tab"],
    ["buildConsensus", "{sample}/{locus}/reports/{sample}_BC_BC_table.tab"],
	["total", "{sample}/{locus}/reports/{sample}_BC_TOTAL_headers.tab"],
    ["unique", "{sample}/{locus}/reports/{sample}_BC_UNIQUE_headers.tab"],
    ["unique_atleast2", "{sample}/{locus}/reports/{sample}_BC_ATLEAST2_headers.tab"],
    ["align", "{sample}/{locus}/alignment/{sample}_v_align_non-personalized.tsv"],
    ["align_personalized", "{sample}/{locus}/alignment/{sample}_v_align_non-personalized.tsv"],
    ["clones", "{sample}/{locus}/clones/{sample}_{locus}_clone_freqs.csv"],
]
